//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOCDMofApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apps_processes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apps_processes()
        {
            this.Apps_REF_processes = new HashSet<Apps_REF_processes>();
        }
    
        public int Id { get; set; }
        public string sp_name { get; set; }
        public string sp_desc { get; set; }
        public string sp_database { get; set; }
        public string sp_databse__user { get; set; }
        public string sp_databse__pass { get; set; }
        public string sp_datasource { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apps_REF_processes> Apps_REF_processes { get; set; }
    }
}
