//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOCDMofApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apps_Document
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public string media { get; set; }
        public string media_type { get; set; }
        public int Apps_UsersRoleId { get; set; }
        public string tags { get; set; }
    
        public virtual Apps_UsersRole Apps_UsersRole { get; set; }
    }
}
