//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOCDMofApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identity
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string logo { get; set; }
        public string headerColor { get; set; }
        public string aboutDesc { get; set; }
        public string contactDesc { get; set; }
        public string footerDesc { get; set; }
    }
}
