//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOCDMofApps.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apps> Apps { get; set; }
        public virtual DbSet<Apps_Category> Apps_Category { get; set; }
        public virtual DbSet<Apps_Type> Apps_Type { get; set; }
        public virtual DbSet<Apps_Users> Apps_Users { get; set; }
        public virtual DbSet<Apps_Document> Apps_Document { get; set; }
        public virtual DbSet<Apps_UsersRole> Apps_UsersRole { get; set; }
        public virtual DbSet<vw_search> vw_search { get; set; }
        public virtual DbSet<Apps_reports> Apps_reports { get; set; }
        public virtual DbSet<Apps_reports_params> Apps_reports_params { get; set; }
        public virtual DbSet<Apps_processes> Apps_processes { get; set; }
        public virtual DbSet<Apps_REF_processes> Apps_REF_processes { get; set; }
        public virtual DbSet<Identity> Identities { get; set; }
        public virtual DbSet<Apps_password> Apps_password { get; set; }
    }
}
