//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apps_reports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apps_reports()
        {
            this.Apps_reports_params = new HashSet<Apps_reports_params>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public int FK_REF_userRolesId { get; set; }
        public bool paramCheck { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apps_reports_params> Apps_reports_params { get; set; }
        public virtual Apps_UsersRole Apps_UsersRole { get; set; }
    }
}
