//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPS_notices
    {
        public string Id { get; set; }
        public string content { get; set; }
        public System.DateTime dateModified { get; set; }
        public System.DateTime expires { get; set; }
        public string ipRestriction { get; set; }
        public string link { get; set; }
    }
}
