//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apps
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public int Apps_CategoryId { get; set; }
        public string url { get; set; }
        public int Apps_TypeId { get; set; }
        public string loc { get; set; }
        public Nullable<bool> featured { get; set; }
        public Nullable<bool> active { get; set; }
        public string image { get; set; }
        public int Apps_UsersRoleId { get; set; }
    
        public virtual Apps_Category Apps_Category { get; set; }
        public virtual Apps_Type Apps_Type { get; set; }
        public virtual Apps_UsersRole Apps_UsersRole { get; set; }
    }
}
